### PR TITLE
Darkmode Button :D

### PR DESCRIPTION
**Pull request by IamTregsthedev**
This adds a Darkmode Button to the site

### CODE REVIEW

**Comment by KennethSweezy** [comment]
@IamTregsthedev The dark mode button is not displaying for me.

**Comment by IamTregsthedev** [comment]
> @IamTregsthedev The dark mode button is not displaying for me.

Me too, I'm gonna fix this

**Comment by Andreto** [comment]
It looks pretty bad.
Especially the inputs. 
GoboDarkMode1

Something like this would be more like it:
Skärmklipp

Can that be done somehow, or is the script similar to Dark Reader?

**Comment by IamTregsthedev** [comment]
I'm going to bring this to the creator of it, We could our own Darkmode?

**Comment by KennethSweezy** [comment]
@IamTregsthedev I agree it looks pretty bad. Especially things like Gobo, inputs (like @Andreto mentioned), and the GitHub Link in the top corner.

**Pull request merged**
